### ISSUE TITLE
Module 'ChromeCastCore' not found`

### ISSUE THREAD

**Issue by DannyCork** [insidegui/AppleEvents#12]
When building using xCode Version 8.2 (8C38) on Mac OS 10.12.5 (16F73)

`/Users/d/Sites/AppleEvents/Apple Events/EVTChromecastViewController.m:12:9: Module 'ChromeCastCore' not found`

There is however a @import ChromeCastCore; right there.

**Comment by insidegui** [comment]
You have to clone it with `--recursive`
