### ISSUE TITLE
Visual anomaly when tab bar is shown

### ISSUE THREAD

**Issue by SoneeJohn** [insidegui/AppleEvents#2]
I noticed this when the tab bar is shown.

![screen shot 2016-09-08 at 10 27 02 am](https://cloud.githubusercontent.com/assets/4827301/18353096/d093cdf8-75ae-11e6-9687-e78c82fb1c0b.png)

Not a huge issue but something to bare in mind.

**Comment by insidegui** [comment]
Good to know. I must disable this because the app doesn't support multiple windows / tabs. Thanks for reporting.
