### ISSUE TITLE
Warning + No View error

### ISSUE THREAD

**Issue by marthesselink** [insidegui/AppleEvents#3]
When opening the app I immediatly get this warning. When I click OK everything stays the samen and nothing loads.
<img src="https://s14.postimg.io/69eoaj3up/Screen_Shot_2016_09_09_at_10_41_22_AM.png">
This ^

**Comment by insidegui** [comment]
Duplicate of #1. Which language/timezone are you using on your system?

**Comment by insidegui** [comment]
I am closing this one, if you have any comments please keep posting on #1 . Thanks.
