### ISSUE TITLE
[Question] HD support?

### ISSUE THREAD

**Issue by ngocphamm** [insidegui/AppleEvents#4]
Firstly, thank you for this interesting app! It works fine for me on 10.12, and a Chromecast 2.

This is just a question, and it may happen that I know nothing, which is very likely.

Does this app support HD livestream? I didn't look like it when I tried to play the Apple Event on September 7th.

**Comment by insidegui** [comment]
Hi @ngocphamm! Apple's streaming uses an adaptive system, it will automatically switch between HD/SD depending on whether the system thinks your connection can keep up or not. Unfortunately there is no way to manually select the video quality.

**Comment by ngocphamm** [comment]
Interesting to know that, as I don't have a really fast Internet connection, @insidegui. However, I was able to stream 4K movies last night with no lag issue whatsoever. I wonder what would make Apple thinks I can only do 720p video there.

**Comment by insidegui** [comment]
I'm not sure these events are available in 1080p, I think they only go up to 720p for streaming. They do provide them in 1080p on iTunes and YouTube but that's a different system from what this app is using ;)

**Comment by ngocphamm** [comment]
Oh... I see. Good to know. Thank you! 👍
