### ISSUE TITLE
Where did you get the API key?

### ISSUE THREAD

**Issue by San-Jeevan** [insidegui/AppleEvents#6]
Don't really wanna use yours since its private.
Where did you get it?

**Comment by San-Jeevan** [comment]
nvm, it was api key for crash lytics

**Comment by insidegui** [comment]
Hi @San-Jeevan! Apple's API doesn't require an API key. Take a look at [EVTEnvironment.m](https://github.com/insidegui/AppleEvents/blob/master/Apple%20Events/EVTEnvironment.m), you'll find all the API URLs in there.
