### ISSUE TITLE
why changed download scheme?

### ISSUE THREAD

**Issue by muescha** [insidegui/AppleEvents#8]
why you changed the binary archive naming adding a `_r` from 

`AppleEvents_v#VERSION#.zip`
to
`AppleEvents_v#VERSION#_r.zip`

**Comment by insidegui** [comment]
Because I had initially added a wrong file to 0.7 and GitHub didn't let me reupload with the same name.

**Comment by muescha** [comment]
ah ok - i had to change the download path ;)

**Comment by insidegui** [comment]
Ok. Thanks :)
